name: Build and publish

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx6g
      TYPESENSE_HOST: typesense.acdh-dev.oeaw.ac.at
      TYPESENSE_PORT: 443
      TYPESENSE_PROTOCOL: https
      TYPESENSE_API_KEY: ${{secrets.TYPESENSE_API_KEY}}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: set up uv (Python)
        uses: astral-sh/setup-uv@v8.1.0
      - name: Install Python dependencies
        run: |
          uv sync
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
      - name: Fetch the data
        run: ./build_app/scripts/fetch_data.sh
      - name: Fetch imprint
        run: ./scripts/dl_imprint.sh
      - name: Build the app
        run: ant -f build_app/xslt/build.xml
      - name: Rebuild Typesense index
        run: ./build_app/scripts/make_ts_index.py
      - name: Setup Pages
        uses: actions/configure-pages@v6
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
